name: CI

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install
        run: npm ci
      - name: (OIDC) show id-token example
        run: |
          echo "NOTE: OIDC provider must be configured in your cloud provider. This step prints a token example (audience must match provider config)"
          echo "Requesting id token..."
          gh auth refresh -h github.com -s workflow:write || true
          node -e "console.log('id-token placeholder')"
      - name: Lint
        run: npm run lint
      - name: Typecheck
        run: npm run typecheck
