name: Supabase Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install supabase CLI (official)
        run: |
          set -e
          ARCH="x86_64"
          TAG=$(curl -s https://api.github.com/repos/supabase/cli/releases/latest | jq -r .tag_name)
          URL="https://github.com/supabase/cli/releases/download/${TAG}/supabase_${TAG#v}_linux_${ARCH}.tgz"
          echo "Downloading $URL"
          curl -sL "$URL" -o supabase.tgz
          tar -xzf supabase.tgz
          sudo mv supabase /usr/local/bin/supabase
          supabase --version

      - name: Run supabase deploy script
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
        run: |
          pwsh -NoLogo -NoProfile -NonInteractive ./infra/supabase/run_deploy_locally.ps1
